/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencb_hpg_bigdata_core_NativeAligner */

#ifndef _Included_org_opencb_hpg_bigdata_core_NativeAligner
#define _Included_org_opencb_hpg_bigdata_core_NativeAligner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opencb_hpg_bigdata_core_NativeAligner
 * Method:    load_index
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_opencb_hpg_bigdata_core_NativeAligner_load_1index
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_opencb_hpg_bigdata_core_NativeAligner
 * Method:    free_index
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_opencb_hpg_bigdata_core_NativeAligner_free_1index
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_opencb_hpg_bigdata_core_NativeAligner
 * Method:    map
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_opencb_hpg_bigdata_core_NativeAligner_map
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
