/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencb_hpg_bigdata_core_NativeSupport */

#ifndef _Included_org_opencb_hpg_bigdata_core_NativeSupport
#define _Included_org_opencb_hpg_bigdata_core_NativeSupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opencb_hpg_bigdata_core_NativeSupport
 * Method:    bam2ga
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_opencb_hpg_bigdata_core_NativeSupport_bam2ga
  (JNIEnv *, jobject, jstring, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
