/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
public enum ClinicalSignificance {
  benign, likely_benign, VUS, likely_pathogenic, pathogenic, uncertain_significance  ;
}
