/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
public class ClinVar {
   private String accession;
   private String clinicalSignificance;
   private java.util.List<String> traits;
   private java.util.List<String> geneNames;
   private String reviewStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ClinVar() {}

  /**
   * All-args constructor.
   */
  public ClinVar(String accession, String clinicalSignificance, java.util.List<String> traits, java.util.List<String> geneNames, String reviewStatus) {
    this.accession = accession;
    this.clinicalSignificance = clinicalSignificance;
    this.traits = traits;
    this.geneNames = geneNames;
    this.reviewStatus = reviewStatus;
  }

  /**
   * Gets the value of the 'accession' field.
   */
  public String getAccession() {
    return accession;
  }

  /**
   * Sets the value of the 'accession' field.
   * @param value the value to set.
   */
  public void setAccession(String value) {
    this.accession = value;
  }

  /**
   * Gets the value of the 'clinicalSignificance' field.
   */
  public String getClinicalSignificance() {
    return clinicalSignificance;
  }

  /**
   * Sets the value of the 'clinicalSignificance' field.
   * @param value the value to set.
   */
  public void setClinicalSignificance(String value) {
    this.clinicalSignificance = value;
  }

  /**
   * Gets the value of the 'traits' field.
   */
  public java.util.List<String> getTraits() {
    return traits;
  }

  /**
   * Sets the value of the 'traits' field.
   * @param value the value to set.
   */
  public void setTraits(java.util.List<String> value) {
    this.traits = value;
  }

  /**
   * Gets the value of the 'geneNames' field.
   */
  public java.util.List<String> getGeneNames() {
    return geneNames;
  }

  /**
   * Sets the value of the 'geneNames' field.
   * @param value the value to set.
   */
  public void setGeneNames(java.util.List<String> value) {
    this.geneNames = value;
  }

  /**
   * Gets the value of the 'reviewStatus' field.
   */
  public String getReviewStatus() {
    return reviewStatus;
  }

  /**
   * Sets the value of the 'reviewStatus' field.
   * @param value the value to set.
   */
  public void setReviewStatus(String value) {
    this.reviewStatus = value;
  }
}
