/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Cytoband {
   private String stain;
   private String name;
   private Integer start;
   private Integer end;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Cytoband() {}

  /**
   * All-args constructor.
   */
  public Cytoband(String stain, String name, Integer start, Integer end) {
    this.stain = stain;
    this.name = name;
    this.start = start;
    this.end = end;
  }

  /**
   * Gets the value of the 'stain' field.
   */
  public String getStain() {
    return stain;
  }

  /**
   * Sets the value of the 'stain' field.
   * @param value the value to set.
   */
  public void setStain(String value) {
    this.stain = value;
  }

  /**
   * Gets the value of the 'name' field.
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'start' field.
   */
  public Integer getStart() {
    return start;
  }

  /**
   * Sets the value of the 'start' field.
   * @param value the value to set.
   */
  public void setStart(Integer value) {
    this.start = value;
  }

  /**
   * Gets the value of the 'end' field.
   */
  public Integer getEnd() {
    return end;
  }

  /**
   * Sets the value of the 'end' field.
   * @param value the value to set.
   */
  public void setEnd(Integer value) {
    this.end = value;
  }
}
