/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
/** This is the list of ethnics in ONS16

* `D`:  Mixed: White and Black Caribbean
* `E`:  Mixed: White and Black African
* `F`:  Mixed: White and Asian
* `G`:  Mixed: Any other mixed background
* `A`:  White: British
* `B`:  White: Irish
* `C`:  White: Any other White background
* `L`:  Asian or Asian British: Any other Asian background
* `M`:  Black or Black British: Caribbean
* `N`:  Black or Black British: African
* `H`:  Asian or Asian British: Indian
* `J`:  Asian or Asian British: Pakistani
* `K`:  Asian or Asian British: Bangladeshi
* `P`:  Black or Black British: Any other Black background
* `S`:  Other Ethnic Groups: Any other ethnic group
* `R`:  Other Ethnic Groups: Chinese
* `Z`:  Not stated */
@org.apache.avro.specific.AvroGenerated
public enum EthnicCategory { 
  D, E, F, G, A, B, C, L, M, N, H, J, K, P, S, R, Z  ;
}
