/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface EvidenceProtocol {
 public interface Callback extends org.opencb.biodata.models.variant.avro.EvidenceProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = org.opencb.biodata.models.variant.avro.EvidenceProtocol.PROTOCOL;
  }
}