/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
/** The submission information */
public class EvidenceSubmission {
  /** The submitter */
   private String submitter;
  /** The submission date */
   private String date;
  /** The submission id */
   private String id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EvidenceSubmission() {}

  /**
   * All-args constructor.
   */
  public EvidenceSubmission(String submitter, String date, String id) {
    this.submitter = submitter;
    this.date = date;
    this.id = id;
  }

  /**
   * Gets the value of the 'submitter' field.
   * The submitter   */
  public String getSubmitter() {
    return submitter;
  }

  /**
   * Sets the value of the 'submitter' field.
   * The submitter   * @param value the value to set.
   */
  public void setSubmitter(String value) {
    this.submitter = value;
  }

  /**
   * Gets the value of the 'date' field.
   * The submission date   */
  public String getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * The submission date   * @param value the value to set.
   */
  public void setDate(String value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'id' field.
   * The submission id   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * The submission id   * @param value the value to set.
   */
  public void setId(String value) {
    this.id = value;
  }
}
