/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
public class ExonOverlap {
   private String number;
   private Float percentage;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ExonOverlap() {}

  /**
   * All-args constructor.
   */
  public ExonOverlap(String number, Float percentage) {
    this.number = number;
    this.percentage = percentage;
  }

  /**
   * Gets the value of the 'number' field.
   */
  public String getNumber() {
    return number;
  }

  /**
   * Sets the value of the 'number' field.
   * @param value the value to set.
   */
  public void setNumber(String value) {
    this.number = value;
  }

  /**
   * Gets the value of the 'percentage' field.
   */
  public Float getPercentage() {
    return percentage;
  }

  /**
   * Sets the value of the 'percentage' field.
   * @param value the value to set.
   */
  public void setPercentage(Float value) {
    this.percentage = value;
  }
}
