/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
public class Expression {
   private String geneName;
   private String transcriptId;
   private String experimentalFactor;
   private String factorValue;
   private String experimentId;
   private String technologyPlatform;
   private String expression;
   private Float pvalue;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Expression() {}

  /**
   * All-args constructor.
   */
  public Expression(String geneName, String transcriptId, String experimentalFactor, String factorValue, String experimentId, String technologyPlatform, String expression, Float pvalue) {
    this.geneName = geneName;
    this.transcriptId = transcriptId;
    this.experimentalFactor = experimentalFactor;
    this.factorValue = factorValue;
    this.experimentId = experimentId;
    this.technologyPlatform = technologyPlatform;
    this.expression = expression;
    this.pvalue = pvalue;
  }

  /**
   * Gets the value of the 'geneName' field.
   */
  public String getGeneName() {
    return geneName;
  }

  /**
   * Sets the value of the 'geneName' field.
   * @param value the value to set.
   */
  public void setGeneName(String value) {
    this.geneName = value;
  }

  /**
   * Gets the value of the 'transcriptId' field.
   */
  public String getTranscriptId() {
    return transcriptId;
  }

  /**
   * Sets the value of the 'transcriptId' field.
   * @param value the value to set.
   */
  public void setTranscriptId(String value) {
    this.transcriptId = value;
  }

  /**
   * Gets the value of the 'experimentalFactor' field.
   */
  public String getExperimentalFactor() {
    return experimentalFactor;
  }

  /**
   * Sets the value of the 'experimentalFactor' field.
   * @param value the value to set.
   */
  public void setExperimentalFactor(String value) {
    this.experimentalFactor = value;
  }

  /**
   * Gets the value of the 'factorValue' field.
   */
  public String getFactorValue() {
    return factorValue;
  }

  /**
   * Sets the value of the 'factorValue' field.
   * @param value the value to set.
   */
  public void setFactorValue(String value) {
    this.factorValue = value;
  }

  /**
   * Gets the value of the 'experimentId' field.
   */
  public String getExperimentId() {
    return experimentId;
  }

  /**
   * Sets the value of the 'experimentId' field.
   * @param value the value to set.
   */
  public void setExperimentId(String value) {
    this.experimentId = value;
  }

  /**
   * Gets the value of the 'technologyPlatform' field.
   */
  public String getTechnologyPlatform() {
    return technologyPlatform;
  }

  /**
   * Sets the value of the 'technologyPlatform' field.
   * @param value the value to set.
   */
  public void setTechnologyPlatform(String value) {
    this.technologyPlatform = value;
  }

  /**
   * Gets the value of the 'expression' field.
   */
  public String getExpression() {
    return expression;
  }

  /**
   * Sets the value of the 'expression' field.
   * @param value the value to set.
   */
  public void setExpression(String value) {
    this.expression = value;
  }

  /**
   * Gets the value of the 'pvalue' field.
   */
  public Float getPvalue() {
    return pvalue;
  }

  /**
   * Sets the value of the 'pvalue' field.
   * @param value the value to set.
   */
  public void setPvalue(Float value) {
    this.pvalue = value;
  }
}
