/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
/** The feature types */
public enum FeatureTypes {
  RegulatoryRegion, Gene, Transcript, Protein  ;
}
