/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
public class GeneDrugInteraction {
   private String geneName;
   private String drugName;
   private String source;
   private String studyType;
   private String type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GeneDrugInteraction() {}

  /**
   * All-args constructor.
   */
  public GeneDrugInteraction(String geneName, String drugName, String source, String studyType, String type) {
    this.geneName = geneName;
    this.drugName = drugName;
    this.source = source;
    this.studyType = studyType;
    this.type = type;
  }

  /**
   * Gets the value of the 'geneName' field.
   */
  public String getGeneName() {
    return geneName;
  }

  /**
   * Sets the value of the 'geneName' field.
   * @param value the value to set.
   */
  public void setGeneName(String value) {
    this.geneName = value;
  }

  /**
   * Gets the value of the 'drugName' field.
   */
  public String getDrugName() {
    return drugName;
  }

  /**
   * Sets the value of the 'drugName' field.
   * @param value the value to set.
   */
  public void setDrugName(String value) {
    this.drugName = value;
  }

  /**
   * Gets the value of the 'source' field.
   */
  public String getSource() {
    return source;
  }

  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(String value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'studyType' field.
   */
  public String getStudyType() {
    return studyType;
  }

  /**
   * Sets the value of the 'studyType' field.
   * @param value the value to set.
   */
  public void setStudyType(String value) {
    this.studyType = value;
  }

  /**
   * Gets the value of the 'type' field.
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(String value) {
    this.type = value;
  }
}
