/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
public class Genotype {
   private String reference;
   private String alternate;
   private java.util.List<Integer> allelesIdx;
   private boolean phased;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Genotype() {}

  /**
   * All-args constructor.
   */
  public Genotype(String reference, String alternate, java.util.List<Integer> allelesIdx, Boolean phased) {
    this.reference = reference;
    this.alternate = alternate;
    this.allelesIdx = allelesIdx;
    this.phased = phased;
  }

  /**
   * Gets the value of the 'reference' field.
   */
  public String getReference() {
    return reference;
  }

  /**
   * Sets the value of the 'reference' field.
   * @param value the value to set.
   */
  public void setReference(String value) {
    this.reference = value;
  }

  /**
   * Gets the value of the 'alternate' field.
   */
  public String getAlternate() {
    return alternate;
  }

  /**
   * Sets the value of the 'alternate' field.
   * @param value the value to set.
   */
  public void setAlternate(String value) {
    this.alternate = value;
  }

  /**
   * Gets the value of the 'allelesIdx' field.
   */
  public java.util.List<Integer> getAllelesIdx() {
    return allelesIdx;
  }

  /**
   * Sets the value of the 'allelesIdx' field.
   * @param value the value to set.
   */
  public void setAllelesIdx(java.util.List<Integer> value) {
    this.allelesIdx = value;
  }

  /**
   * Gets the value of the 'phased' field.
   */
  public Boolean getPhased() {
    return phased;
  }

  /**
   * Sets the value of the 'phased' field.
   * @param value the value to set.
   */
  public void setPhased(Boolean value) {
    this.phased = value;
  }
}
