/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
public class Gwas {
   private String snpIdCurrent;
   private java.util.List<String> traits;
   private double riskAlleleFrequency;
   private String reportedGenes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Gwas() {}

  /**
   * All-args constructor.
   */
  public Gwas(String snpIdCurrent, java.util.List<String> traits, Double riskAlleleFrequency, String reportedGenes) {
    this.snpIdCurrent = snpIdCurrent;
    this.traits = traits;
    this.riskAlleleFrequency = riskAlleleFrequency;
    this.reportedGenes = reportedGenes;
  }

  /**
   * Gets the value of the 'snpIdCurrent' field.
   */
  public String getSnpIdCurrent() {
    return snpIdCurrent;
  }

  /**
   * Sets the value of the 'snpIdCurrent' field.
   * @param value the value to set.
   */
  public void setSnpIdCurrent(String value) {
    this.snpIdCurrent = value;
  }

  /**
   * Gets the value of the 'traits' field.
   */
  public java.util.List<String> getTraits() {
    return traits;
  }

  /**
   * Sets the value of the 'traits' field.
   * @param value the value to set.
   */
  public void setTraits(java.util.List<String> value) {
    this.traits = value;
  }

  /**
   * Gets the value of the 'riskAlleleFrequency' field.
   */
  public Double getRiskAlleleFrequency() {
    return riskAlleleFrequency;
  }

  /**
   * Sets the value of the 'riskAlleleFrequency' field.
   * @param value the value to set.
   */
  public void setRiskAlleleFrequency(Double value) {
    this.riskAlleleFrequency = value;
  }

  /**
   * Gets the value of the 'reportedGenes' field.
   */
  public String getReportedGenes() {
    return reportedGenes;
  }

  /**
   * Sets the value of the 'reportedGenes' field.
   * @param value the value to set.
   */
  public void setReportedGenes(String value) {
    this.reportedGenes = value;
  }
}
