/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
/** The entity representing a phenotype and its inheritance pattern. */
public class HeritableTrait {
  /** The trait (e.g.: HPO term, MIM term, DO term etc.) */
   private String trait;
  /** The mode of inheritance */
   private String inheritanceMode;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public HeritableTrait() {}

  /**
   * All-args constructor.
   */
  public HeritableTrait(String trait, String inheritanceMode) {
    this.trait = trait;
    this.inheritanceMode = inheritanceMode;
  }
  
  /**
   * Gets the value of the 'trait' field.
   * The trait (e.g.: HPO term, MIM term, DO term etc.)   */
  public String getTrait() {
    return trait;
  }

  /**
   * Sets the value of the 'trait' field.
   * The trait (e.g.: HPO term, MIM term, DO term etc.)   * @param value the value to set.
   */
  public void setTrait(String value) {
    this.trait = value;
  }

  /**
   * Gets the value of the 'inheritanceMode' field.
   * The mode of inheritance   */
  public String getInheritanceMode() {
    return inheritanceMode;
  }

  /**
   * Sets the value of the 'inheritanceMode' field.
   * The mode of inheritance   * @param value the value to set.
   */
  public void setInheritanceMode(String value) {
    this.inheritanceMode = value;
  }
}
