/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
/** A property in the form of name-value pair.
    Names are restricted to ontology ids, they should be checked against existing ontologies in resources like
    Ontology Lookup Service. */
public class Property {
  /** The ontology term id or accession in OBO format ${ONTOLOGY_ID}:${TERM_ID} (http://www.obofoundry.org/id-policy.html) */
   private String id;
  /** The ontology term name */
   private String name;
  /** Optional value for the ontology term, the type of the value is not checked
        (i.e.: we could set the pvalue term to "significant" or to "0.0001") */
   private String value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Property() {}

  /**
   * All-args constructor.
   */
  public Property(String id, String name, String value) {
    this.id = id;
    this.name = name;
    this.value = value;
  }

  /**
   * Gets the value of the 'id' field.
   * The ontology term id or accession in OBO format ${ONTOLOGY_ID}:${TERM_ID} (http://www.obofoundry.org/id-policy.html)   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * The ontology term id or accession in OBO format ${ONTOLOGY_ID}:${TERM_ID} (http://www.obofoundry.org/id-policy.html)   * @param value the value to set.
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * The ontology term name   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * The ontology term name   * @param value the value to set.
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'value' field.
   * Optional value for the ontology term, the type of the value is not checked
        (i.e.: we could set the pvalue term to "significant" or to "0.0001")   */
  public String getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * Optional value for the ontology term, the type of the value is not checked
        (i.e.: we could set the pvalue term to "significant" or to "0.0001")   * @param value the value to set.
   */
  public void setValue(String value) {
    this.value = value;
  }
}
