/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
public class Repeat {
   private String id;
   private String chromosome;
   private Integer start;
   private Integer end;
   private Integer period;
   private Float copyNumber;
   private Float percentageMatch;
   private Float score;
   private String sequence;
   private String source;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Repeat() {}

  /**
   * All-args constructor.
   */
  public Repeat(String id, String chromosome, Integer start, Integer end, Integer period, Float copyNumber, Float percentageMatch, Float score, String sequence, String source) {
    this.id = id;
    this.chromosome = chromosome;
    this.start = start;
    this.end = end;
    this.period = period;
    this.copyNumber = copyNumber;
    this.percentageMatch = percentageMatch;
    this.score = score;
    this.sequence = sequence;
    this.source = source;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'chromosome' field.
   */
  public String getChromosome() {
    return chromosome;
  }

  /**
   * Sets the value of the 'chromosome' field.
   * @param value the value to set.
   */
  public void setChromosome(String value) {
    this.chromosome = value;
  }

  /**
   * Gets the value of the 'start' field.
   */
  public Integer getStart() {
    return start;
  }

  /**
   * Sets the value of the 'start' field.
   * @param value the value to set.
   */
  public void setStart(Integer value) {
    this.start = value;
  }

  /**
   * Gets the value of the 'end' field.
   */
  public Integer getEnd() {
    return end;
  }

  /**
   * Sets the value of the 'end' field.
   * @param value the value to set.
   */
  public void setEnd(Integer value) {
    this.end = value;
  }

  /**
   * Gets the value of the 'period' field.
   */
  public Integer getPeriod() {
    return period;
  }

  /**
   * Sets the value of the 'period' field.
   * @param value the value to set.
   */
  public void setPeriod(Integer value) {
    this.period = value;
  }

  /**
   * Gets the value of the 'copyNumber' field.
   */
  public Float getCopyNumber() {
    return copyNumber;
  }

  /**
   * Sets the value of the 'copyNumber' field.
   * @param value the value to set.
   */
  public void setCopyNumber(Float value) {
    this.copyNumber = value;
  }

  /**
   * Gets the value of the 'percentageMatch' field.
   */
  public Float getPercentageMatch() {
    return percentageMatch;
  }

  /**
   * Sets the value of the 'percentageMatch' field.
   * @param value the value to set.
   */
  public void setPercentageMatch(Float value) {
    this.percentageMatch = value;
  }

  /**
   * Gets the value of the 'score' field.
   */
  public Float getScore() {
    return score;
  }

  /**
   * Sets the value of the 'score' field.
   * @param value the value to set.
   */
  public void setScore(Float value) {
    this.score = value;
  }

  /**
   * Gets the value of the 'sequence' field.
   */
  public String getSequence() {
    return sequence;
  }

  /**
   * Sets the value of the 'sequence' field.
   * @param value the value to set.
   */
  public void setSequence(String value) {
    this.sequence = value;
  }

  /**
   * Gets the value of the 'source' field.
   */
  public String getSource() {
    return source;
  }

  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(String value) {
    this.source = value;
  }
}
