/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
public class Score {
   private double score;
   private String source;
   private String description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Score() {}

  /**
   * All-args constructor.
   */
  public Score(Double score, String source, String description) {
    this.score = score;
    this.source = source;
    this.description = description;
  }

  /**
   * Gets the value of the 'score' field.
   */
  public Double getScore() {
    return score;
  }

  /**
   * Sets the value of the 'score' field.
   * @param value the value to set.
   */
  public void setScore(Double value) {
    this.score = value;
  }

  /**
   * Gets the value of the 'source' field.
   */
  public String getSource() {
    return source;
  }

  /**
   * Sets the value of the 'source' field.
   * @param value the value to set.
   */
  public void setSource(String value) {
    this.source = value;
  }

  /**
   * Gets the value of the 'description' field.
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(String value) {
    this.description = value;
  }
}
