/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
/** The somatic information. */
public class SomaticInformation {
  /** The primary site */
   private String primarySite;
  /** The primary site subtype */
   private String siteSubtype;
  /** The primary histology */
   private String primaryHistology;
  /** The histology subtype */
   private String histologySubtype;
  /** The tumour origin */
   private String tumourOrigin;
  /** The sample source, e.g. blood-bone marrow, cell-line, pancreatic */
   private String sampleSource;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SomaticInformation() {}

  /**
   * All-args constructor.
   */
  public SomaticInformation(String primarySite, String siteSubtype, String primaryHistology, String histologySubtype, String tumourOrigin, String sampleSource) {
    this.primarySite = primarySite;
    this.siteSubtype = siteSubtype;
    this.primaryHistology = primaryHistology;
    this.histologySubtype = histologySubtype;
    this.tumourOrigin = tumourOrigin;
    this.sampleSource = sampleSource;
  }

  /**
   * Gets the value of the 'primarySite' field.
   * The primary site   */
  public String getPrimarySite() {
    return primarySite;
  }

  /**
   * Sets the value of the 'primarySite' field.
   * The primary site   * @param value the value to set.
   */
  public void setPrimarySite(String value) {
    this.primarySite = value;
  }

  /**
   * Gets the value of the 'siteSubtype' field.
   * The primary site subtype   */
  public String getSiteSubtype() {
    return siteSubtype;
  }

  /**
   * Sets the value of the 'siteSubtype' field.
   * The primary site subtype   * @param value the value to set.
   */
  public void setSiteSubtype(String value) {
    this.siteSubtype = value;
  }

  /**
   * Gets the value of the 'primaryHistology' field.
   * The primary histology   */
  public String getPrimaryHistology() {
    return primaryHistology;
  }

  /**
   * Sets the value of the 'primaryHistology' field.
   * The primary histology   * @param value the value to set.
   */
  public void setPrimaryHistology(String value) {
    this.primaryHistology = value;
  }

  /**
   * Gets the value of the 'histologySubtype' field.
   * The histology subtype   */
  public String getHistologySubtype() {
    return histologySubtype;
  }

  /**
   * Sets the value of the 'histologySubtype' field.
   * The histology subtype   * @param value the value to set.
   */
  public void setHistologySubtype(String value) {
    this.histologySubtype = value;
  }

  /**
   * Gets the value of the 'tumourOrigin' field.
   * The tumour origin   */
  public String getTumourOrigin() {
    return tumourOrigin;
  }

  /**
   * Sets the value of the 'tumourOrigin' field.
   * The tumour origin   * @param value the value to set.
   */
  public void setTumourOrigin(String value) {
    this.tumourOrigin = value;
  }

  /**
   * Gets the value of the 'sampleSource' field.
   * The sample source, e.g. blood-bone marrow, cell-line, pancreatic   */
  public String getSampleSource() {
    return sampleSource;
  }

  /**
   * Sets the value of the 'sampleSource' field.
   * The sample source, e.g. blood-bone marrow, cell-line, pancreatic   * @param value the value to set.
   */
  public void setSampleSource(String value) {
    this.sampleSource = value;
  }
}
