/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
public class StructuralVariation {
   private Integer ciStartLeft;
   private Integer ciStartRight;
   private Integer ciEndLeft;
   private Integer ciEndRight;
  /** * Number of copies for CNV variants. */
   private Integer copyNumber;
  /** * Inserted sequence for long INS
        * */
   private String leftSvInsSeq;
   private String rightSvInsSeq;
  /** * Structural variation type: COPY_NUMBER_GAIN, COPY_NUMBER_LOSS, TANDEM_DUPLICATION, ... */
   private String type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StructuralVariation() {}

  /**
   * All-args constructor.
   */
  public StructuralVariation(Integer ciStartLeft, Integer ciStartRight, Integer ciEndLeft, Integer ciEndRight, Integer copyNumber, String leftSvInsSeq, String rightSvInsSeq, String type) {
    this.ciStartLeft = ciStartLeft;
    this.ciStartRight = ciStartRight;
    this.ciEndLeft = ciEndLeft;
    this.ciEndRight = ciEndRight;
    this.copyNumber = copyNumber;
    this.leftSvInsSeq = leftSvInsSeq;
    this.rightSvInsSeq = rightSvInsSeq;
    this.type = type;
  }
  
  /**
   * Gets the value of the 'ciStartLeft' field.
   */
  public Integer getCiStartLeft() {
    return ciStartLeft;
  }

  /**
   * Sets the value of the 'ciStartLeft' field.
   * @param value the value to set.
   */
  public void setCiStartLeft(Integer value) {
    this.ciStartLeft = value;
  }

  /**
   * Gets the value of the 'ciStartRight' field.
   */
  public Integer getCiStartRight() {
    return ciStartRight;
  }

  /**
   * Sets the value of the 'ciStartRight' field.
   * @param value the value to set.
   */
  public void setCiStartRight(Integer value) {
    this.ciStartRight = value;
  }

  /**
   * Gets the value of the 'ciEndLeft' field.
   */
  public Integer getCiEndLeft() {
    return ciEndLeft;
  }

  /**
   * Sets the value of the 'ciEndLeft' field.
   * @param value the value to set.
   */
  public void setCiEndLeft(Integer value) {
    this.ciEndLeft = value;
  }

  /**
   * Gets the value of the 'ciEndRight' field.
   */
  public Integer getCiEndRight() {
    return ciEndRight;
  }

  /**
   * Sets the value of the 'ciEndRight' field.
   * @param value the value to set.
   */
  public void setCiEndRight(Integer value) {
    this.ciEndRight = value;
  }

  /**
   * Gets the value of the 'copyNumber' field.
   * * Number of copies for CNV variants.   */
  public Integer getCopyNumber() {
    return copyNumber;
  }

  /**
   * Sets the value of the 'copyNumber' field.
   * * Number of copies for CNV variants.   * @param value the value to set.
   */
  public void setCopyNumber(Integer value) {
    this.copyNumber = value;
  }

  /**
   * Gets the value of the 'leftSvInsSeq' field.
   * * Inserted sequence for long INS
        *   */
  public String getLeftSvInsSeq() {
    return leftSvInsSeq;
  }

  /**
   * Sets the value of the 'leftSvInsSeq' field.
   * * Inserted sequence for long INS
        *   * @param value the value to set.
   */
  public void setLeftSvInsSeq(String value) {
    this.leftSvInsSeq = value;
  }

  /**
   * Gets the value of the 'rightSvInsSeq' field.
   */
  public String getRightSvInsSeq() {
    return rightSvInsSeq;
  }

  /**
   * Sets the value of the 'rightSvInsSeq' field.
   * @param value the value to set.
   */
  public void setRightSvInsSeq(String value) {
    this.rightSvInsSeq = value;
  }

  /**
   * Gets the value of the 'type' field.
   * * Structural variation type: COPY_NUMBER_GAIN, COPY_NUMBER_LOSS, TANDEM_DUPLICATION, ...   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * * Structural variation type: COPY_NUMBER_GAIN, COPY_NUMBER_LOSS, TANDEM_DUPLICATION, ...   * @param value the value to set.
   */
  public void setType(String value) {
    this.type = value;
  }
}
