/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
public class StudyEntry {
  /** * Unique identifier of the study. */
   private String studyId;
  /** * List of files from the study where the variant was present. */
   private java.util.List<FileEntry> files;
  /** * Alternate alleles that appear along with a variant alternate. */
   private java.util.List<AlternateCoordinate> secondaryAlternates;
  /** * Fields stored for each sample. */
   private java.util.List<String> format;
  /** * Genotypes and other sample-related information. Each position is related
         * with one sample. The content are lists of values in the same order than the
         * format array. The length of this lists must be the same as the format field. */
   private java.util.List<java.util.List<String>> samplesData;
  /** * Statistics of the genomic variation, such as its alleles/genotypes count
         * or its minimum allele frequency, grouped by cohort name. */
   private java.util.Map<String,VariantStats> stats;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StudyEntry() {}

  /**
   * All-args constructor.
   */
  public StudyEntry(String studyId, java.util.List<FileEntry> files, java.util.List<AlternateCoordinate> secondaryAlternates, java.util.List<String> format, java.util.List<java.util.List<String>> samplesData, java.util.Map<String,VariantStats> stats) {
    this.studyId = studyId;
    this.files = files;
    this.secondaryAlternates = secondaryAlternates;
    this.format = format;
    this.samplesData = samplesData;
    this.stats = stats;
  }
  
  /**
   * Gets the value of the 'studyId' field.
   * * Unique identifier of the study.   */
  public String getStudyId() {
    return studyId;
  }

  /**
   * Sets the value of the 'studyId' field.
   * * Unique identifier of the study.   * @param value the value to set.
   */
  public void setStudyId(String value) {
    this.studyId = value;
  }

  /**
   * Gets the value of the 'files' field.
   * * List of files from the study where the variant was present.   */
  public java.util.List<FileEntry> getFiles() {
    return files;
  }

  /**
   * Sets the value of the 'files' field.
   * * List of files from the study where the variant was present.   * @param value the value to set.
   */
  public void setFiles(java.util.List<FileEntry> value) {
    this.files = value;
  }

  /**
   * Gets the value of the 'secondaryAlternates' field.
   * * Alternate alleles that appear along with a variant alternate.   */
  public java.util.List<AlternateCoordinate> getSecondaryAlternates() {
    return secondaryAlternates;
  }

  /**
   * Sets the value of the 'secondaryAlternates' field.
   * * Alternate alleles that appear along with a variant alternate.   * @param value the value to set.
   */
  public void setSecondaryAlternates(java.util.List<AlternateCoordinate> value) {
    this.secondaryAlternates = value;
  }

  /**
   * Gets the value of the 'format' field.
   * * Fields stored for each sample.   */
  public java.util.List<String> getFormat() {
    return format;
  }

  /**
   * Sets the value of the 'format' field.
   * * Fields stored for each sample.   * @param value the value to set.
   */
  public void setFormat(java.util.List<String> value) {
    this.format = value;
  }

  /**
   * Gets the value of the 'samplesData' field.
   * * Genotypes and other sample-related information. Each position is related
         * with one sample. The content are lists of values in the same order than the
         * format array. The length of this lists must be the same as the format field.   */
  public java.util.List<java.util.List<String>> getSamplesData() {
    return samplesData;
  }

  /**
   * Sets the value of the 'samplesData' field.
   * * Genotypes and other sample-related information. Each position is related
         * with one sample. The content are lists of values in the same order than the
         * format array. The length of this lists must be the same as the format field.   * @param value the value to set.
   */
  public void setSamplesData(java.util.List<java.util.List<String>> value) {
    this.samplesData = value;
  }

  /**
   * Gets the value of the 'stats' field.
   * * Statistics of the genomic variation, such as its alleles/genotypes count
         * or its minimum allele frequency, grouped by cohort name.   */
  public java.util.Map<String,VariantStats> getStats() {
    return stats;
  }

  /**
   * Sets the value of the 'stats' field.
   * * Statistics of the genomic variation, such as its alleles/genotypes count
         * or its minimum allele frequency, grouped by cohort name.   * @param value the value to set.
   */
  public void setStats(java.util.Map<String,VariantStats> value) {
    this.stats = value;
  }
}
