/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
public class VariantAnnotation {
   private String chromosome;
   private Integer start;
   private Integer end;
   private String reference;
   private String alternate;
   private String ancestralAllele;
   private String id;
   private java.util.List<Xref> xrefs;
   private java.util.List<String> hgvs;
   private String displayConsequenceType;
   private java.util.List<ConsequenceType> consequenceTypes;
   private java.util.List<PopulationFrequency> populationFrequencies;
   private String minorAllele;
   private Float minorAlleleFreq;
   private java.util.List<Score> conservation;
   private java.util.List<Expression> geneExpression;
   private java.util.List<GeneTraitAssociation> geneTraitAssociation;
   private java.util.List<GeneDrugInteraction> geneDrugInteraction;
   private VariantTraitAssociation variantTraitAssociation;
   private java.util.List<EvidenceEntry> traitAssociation;
   private java.util.List<Score> functionalScore;
   private java.util.List<Cytoband> cytoband;
   private java.util.List<Repeat> repeat;
   private java.util.Map<String,AdditionalAttribute> additionalAttributes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public VariantAnnotation() {}

  /**
   * All-args constructor.
   */
  public VariantAnnotation(String chromosome, Integer start, Integer end, String reference, String alternate, String ancestralAllele, String id, java.util.List<Xref> xrefs, java.util.List<String> hgvs, String displayConsequenceType, java.util.List<ConsequenceType> consequenceTypes, java.util.List<PopulationFrequency> populationFrequencies, String minorAllele, Float minorAlleleFreq, java.util.List<Score> conservation, java.util.List<Expression> geneExpression, java.util.List<GeneTraitAssociation> geneTraitAssociation, java.util.List<GeneDrugInteraction> geneDrugInteraction, VariantTraitAssociation variantTraitAssociation, java.util.List<EvidenceEntry> traitAssociation, java.util.List<Score> functionalScore, java.util.List<Cytoband> cytoband, java.util.List<Repeat> repeat, java.util.Map<String,AdditionalAttribute> additionalAttributes) {
    this.chromosome = chromosome;
    this.start = start;
    this.end = end;
    this.reference = reference;
    this.alternate = alternate;
    this.ancestralAllele = ancestralAllele;
    this.id = id;
    this.xrefs = xrefs;
    this.hgvs = hgvs;
    this.displayConsequenceType = displayConsequenceType;
    this.consequenceTypes = consequenceTypes;
    this.populationFrequencies = populationFrequencies;
    this.minorAllele = minorAllele;
    this.minorAlleleFreq = minorAlleleFreq;
    this.conservation = conservation;
    this.geneExpression = geneExpression;
    this.geneTraitAssociation = geneTraitAssociation;
    this.geneDrugInteraction = geneDrugInteraction;
    this.variantTraitAssociation = variantTraitAssociation;
    this.traitAssociation = traitAssociation;
    this.functionalScore = functionalScore;
    this.cytoband = cytoband;
    this.repeat = repeat;
    this.additionalAttributes = additionalAttributes;
  }
  
  /**
   * Gets the value of the 'chromosome' field.
   */
  public String getChromosome() {
    return chromosome;
  }

  /**
   * Sets the value of the 'chromosome' field.
   * @param value the value to set.
   */
  public void setChromosome(String value) {
    this.chromosome = value;
  }

  /**
   * Gets the value of the 'start' field.
   */
  public Integer getStart() {
    return start;
  }

  /**
   * Sets the value of the 'start' field.
   * @param value the value to set.
   */
  public void setStart(Integer value) {
    this.start = value;
  }

  /**
   * Gets the value of the 'end' field.
   */
  public Integer getEnd() {
    return end;
  }

  /**
   * Sets the value of the 'end' field.
   * @param value the value to set.
   */
  public void setEnd(Integer value) {
    this.end = value;
  }

  /**
   * Gets the value of the 'reference' field.
   */
  public String getReference() {
    return reference;
  }

  /**
   * Sets the value of the 'reference' field.
   * @param value the value to set.
   */
  public void setReference(String value) {
    this.reference = value;
  }

  /**
   * Gets the value of the 'alternate' field.
   */
  public String getAlternate() {
    return alternate;
  }

  /**
   * Sets the value of the 'alternate' field.
   * @param value the value to set.
   */
  public void setAlternate(String value) {
    this.alternate = value;
  }

  /**
   * Gets the value of the 'ancestralAllele' field.
   */
  public String getAncestralAllele() {
    return ancestralAllele;
  }

  /**
   * Sets the value of the 'ancestralAllele' field.
   * @param value the value to set.
   */
  public void setAncestralAllele(String value) {
    this.ancestralAllele = value;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'xrefs' field.
   */
  public java.util.List<Xref> getXrefs() {
    return xrefs;
  }

  /**
   * Sets the value of the 'xrefs' field.
   * @param value the value to set.
   */
  public void setXrefs(java.util.List<Xref> value) {
    this.xrefs = value;
  }

  /**
   * Gets the value of the 'hgvs' field.
   */
  public java.util.List<String> getHgvs() {
    return hgvs;
  }

  /**
   * Sets the value of the 'hgvs' field.
   * @param value the value to set.
   */
  public void setHgvs(java.util.List<String> value) {
    this.hgvs = value;
  }

  /**
   * Gets the value of the 'displayConsequenceType' field.
   */
  public String getDisplayConsequenceType() {
    return displayConsequenceType;
  }

  /**
   * Sets the value of the 'displayConsequenceType' field.
   * @param value the value to set.
   */
  public void setDisplayConsequenceType(String value) {
    this.displayConsequenceType = value;
  }

  /**
   * Gets the value of the 'consequenceTypes' field.
   */
  public java.util.List<ConsequenceType> getConsequenceTypes() {
    return consequenceTypes;
  }

  /**
   * Sets the value of the 'consequenceTypes' field.
   * @param value the value to set.
   */
  public void setConsequenceTypes(java.util.List<ConsequenceType> value) {
    this.consequenceTypes = value;
  }

  /**
   * Gets the value of the 'populationFrequencies' field.
   */
  public java.util.List<PopulationFrequency> getPopulationFrequencies() {
    return populationFrequencies;
  }

  /**
   * Sets the value of the 'populationFrequencies' field.
   * @param value the value to set.
   */
  public void setPopulationFrequencies(java.util.List<PopulationFrequency> value) {
    this.populationFrequencies = value;
  }

  /**
   * Gets the value of the 'minorAllele' field.
   */
  public String getMinorAllele() {
    return minorAllele;
  }

  /**
   * Sets the value of the 'minorAllele' field.
   * @param value the value to set.
   */
  public void setMinorAllele(String value) {
    this.minorAllele = value;
  }

  /**
   * Gets the value of the 'minorAlleleFreq' field.
   */
  public Float getMinorAlleleFreq() {
    return minorAlleleFreq;
  }

  /**
   * Sets the value of the 'minorAlleleFreq' field.
   * @param value the value to set.
   */
  public void setMinorAlleleFreq(Float value) {
    this.minorAlleleFreq = value;
  }

  /**
   * Gets the value of the 'conservation' field.
   */
  public java.util.List<Score> getConservation() {
    return conservation;
  }

  /**
   * Sets the value of the 'conservation' field.
   * @param value the value to set.
   */
  public void setConservation(java.util.List<Score> value) {
    this.conservation = value;
  }

  /**
   * Gets the value of the 'geneExpression' field.
   */
  public java.util.List<Expression> getGeneExpression() {
    return geneExpression;
  }

  /**
   * Sets the value of the 'geneExpression' field.
   * @param value the value to set.
   */
  public void setGeneExpression(java.util.List<Expression> value) {
    this.geneExpression = value;
  }

  /**
   * Gets the value of the 'geneTraitAssociation' field.
   */
  public java.util.List<GeneTraitAssociation> getGeneTraitAssociation() {
    return geneTraitAssociation;
  }

  /**
   * Sets the value of the 'geneTraitAssociation' field.
   * @param value the value to set.
   */
  public void setGeneTraitAssociation(java.util.List<GeneTraitAssociation> value) {
    this.geneTraitAssociation = value;
  }

  /**
   * Gets the value of the 'geneDrugInteraction' field.
   */
  public java.util.List<GeneDrugInteraction> getGeneDrugInteraction() {
    return geneDrugInteraction;
  }

  /**
   * Sets the value of the 'geneDrugInteraction' field.
   * @param value the value to set.
   */
  public void setGeneDrugInteraction(java.util.List<GeneDrugInteraction> value) {
    this.geneDrugInteraction = value;
  }

  /**
   * Gets the value of the 'variantTraitAssociation' field.
   */
  public VariantTraitAssociation getVariantTraitAssociation() {
    return variantTraitAssociation;
  }

  /**
   * Sets the value of the 'variantTraitAssociation' field.
   * @param value the value to set.
   */
  public void setVariantTraitAssociation(VariantTraitAssociation value) {
    this.variantTraitAssociation = value;
  }

  /**
   * Gets the value of the 'traitAssociation' field.
   */
  public java.util.List<EvidenceEntry> getTraitAssociation() {
    return traitAssociation;
  }

  /**
   * Sets the value of the 'traitAssociation' field.
   * @param value the value to set.
   */
  public void setTraitAssociation(java.util.List<EvidenceEntry> value) {
    this.traitAssociation = value;
  }

  /**
   * Gets the value of the 'functionalScore' field.
   */
  public java.util.List<Score> getFunctionalScore() {
    return functionalScore;
  }

  /**
   * Sets the value of the 'functionalScore' field.
   * @param value the value to set.
   */
  public void setFunctionalScore(java.util.List<Score> value) {
    this.functionalScore = value;
  }

  /**
   * Gets the value of the 'cytoband' field.
   */
  public java.util.List<Cytoband> getCytoband() {
    return cytoband;
  }

  /**
   * Sets the value of the 'cytoband' field.
   * @param value the value to set.
   */
  public void setCytoband(java.util.List<Cytoband> value) {
    this.cytoband = value;
  }

  /**
   * Gets the value of the 'repeat' field.
   */
  public java.util.List<Repeat> getRepeat() {
    return repeat;
  }

  /**
   * Sets the value of the 'repeat' field.
   * @param value the value to set.
   */
  public void setRepeat(java.util.List<Repeat> value) {
    this.repeat = value;
  }

  /**
   * Gets the value of the 'additionalAttributes' field.
   */
  public java.util.Map<String,AdditionalAttribute> getAdditionalAttributes() {
    return additionalAttributes;
  }

  /**
   * Sets the value of the 'additionalAttributes' field.
   * @param value the value to set.
   */
  public void setAdditionalAttributes(java.util.Map<String,AdditionalAttribute> value) {
    this.additionalAttributes = value;
  }
}
