/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
public class VariantHardyWeinbergStats {
   private Float chi2;
   private Float pValue;
   private Integer n;
   private Integer n_AA_11;
   private Integer n_Aa_10;
   private Integer n_aa_00;
   private Float e_AA_11;
   private Float e_Aa_10;
   private Float e_aa_00;
   private Float p;
   private Float q;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public VariantHardyWeinbergStats() {}

  /**
   * All-args constructor.
   */
  public VariantHardyWeinbergStats(Float chi2, Float pValue, Integer n, Integer n_AA_11, Integer n_Aa_10, Integer n_aa_00, Float e_AA_11, Float e_Aa_10, Float e_aa_00, Float p, Float q) {
    this.chi2 = chi2;
    this.pValue = pValue;
    this.n = n;
    this.n_AA_11 = n_AA_11;
    this.n_Aa_10 = n_Aa_10;
    this.n_aa_00 = n_aa_00;
    this.e_AA_11 = e_AA_11;
    this.e_Aa_10 = e_Aa_10;
    this.e_aa_00 = e_aa_00;
    this.p = p;
    this.q = q;
  }

  /**
   * Gets the value of the 'chi2' field.
   */
  public Float getChi2() {
    return chi2;
  }

  /**
   * Sets the value of the 'chi2' field.
   * @param value the value to set.
   */
  public void setChi2(Float value) {
    this.chi2 = value;
  }

  /**
   * Gets the value of the 'pValue' field.
   */
  public Float getPValue() {
    return pValue;
  }

  /**
   * Sets the value of the 'pValue' field.
   * @param value the value to set.
   */
  public void setPValue(Float value) {
    this.pValue = value;
  }

  /**
   * Gets the value of the 'n' field.
   */
  public Integer getN() {
    return n;
  }

  /**
   * Sets the value of the 'n' field.
   * @param value the value to set.
   */
  public void setN(Integer value) {
    this.n = value;
  }

  /**
   * Gets the value of the 'n_AA_11' field.
   */
  public Integer getNAA11() {
    return n_AA_11;
  }

  /**
   * Sets the value of the 'n_AA_11' field.
   * @param value the value to set.
   */
  public void setNAA11(Integer value) {
    this.n_AA_11 = value;
  }

  /**
   * Gets the value of the 'n_Aa_10' field.
   */
  public Integer getNAa10() {
    return n_Aa_10;
  }

  /**
   * Sets the value of the 'n_Aa_10' field.
   * @param value the value to set.
   */
  public void setNAa10(Integer value) {
    this.n_Aa_10 = value;
  }

  /**
   * Gets the value of the 'n_aa_00' field.
   */
  public Integer getNAa00() {
    return n_aa_00;
  }

  /**
   * Sets the value of the 'n_aa_00' field.
   * @param value the value to set.
   */
  public void setNAa00(Integer value) {
    this.n_aa_00 = value;
  }

  /**
   * Gets the value of the 'e_AA_11' field.
   */
  public Float getEAA11() {
    return e_AA_11;
  }

  /**
   * Sets the value of the 'e_AA_11' field.
   * @param value the value to set.
   */
  public void setEAA11(Float value) {
    this.e_AA_11 = value;
  }

  /**
   * Gets the value of the 'e_Aa_10' field.
   */
  public Float getEAa10() {
    return e_Aa_10;
  }

  /**
   * Sets the value of the 'e_Aa_10' field.
   * @param value the value to set.
   */
  public void setEAa10(Float value) {
    this.e_Aa_10 = value;
  }

  /**
   * Gets the value of the 'e_aa_00' field.
   */
  public Float getEAa00() {
    return e_aa_00;
  }

  /**
   * Sets the value of the 'e_aa_00' field.
   * @param value the value to set.
   */
  public void setEAa00(Float value) {
    this.e_aa_00 = value;
  }

  /**
   * Gets the value of the 'p' field.
   */
  public Float getP() {
    return p;
  }

  /**
   * Sets the value of the 'p' field.
   * @param value the value to set.
   */
  public void setP(Float value) {
    this.p = value;
  }

  /**
   * Gets the value of the 'q' field.
   */
  public Float getQ() {
    return q;
  }

  /**
   * Sets the value of the 'q' field.
   * @param value the value to set.
   */
  public void setQ(Float value) {
    this.q = value;
  }
}
