/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;

import java.util.Map;

@SuppressWarnings("all")
public class VariantStats {
   private String refAllele;
   private String altAllele;
   private Integer refAlleleCount;
   private Integer altAlleleCount;
   private java.util.Map<String,Integer> genotypesCount;
   private java.util.Map<String,Float> genotypesFreq;
   private Integer missingAlleles;
   private Integer missingGenotypes;
   private Float refAlleleFreq;
   private Float altAlleleFreq;
   private Float maf;
   private Float mgf;
   private String mafAllele;
   private String mgfGenotype;
   private Boolean passedFilters;
   private Integer mendelianErrors;
   private Float casesPercentDominant;
   private Float controlsPercentDominant;
   private Float casesPercentRecessive;
   private Float controlsPercentRecessive;
   private Float quality;
   private Integer numSamples;
   private String variantType;
   private VariantHardyWeinbergStats hw;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public VariantStats() {}

  /**
   * All-args constructor.
   */
  public VariantStats(String refAllele, String altAllele, Integer refAlleleCount, Integer altAlleleCount, java.util.Map<String,Integer> genotypesCount, java.util.Map<String,Float> genotypesFreq, Integer missingAlleles, Integer missingGenotypes, Float refAlleleFreq, Float altAlleleFreq, Float maf, Float mgf, String mafAllele, String mgfGenotype, Boolean passedFilters, Integer mendelianErrors, Float casesPercentDominant, Float controlsPercentDominant, Float casesPercentRecessive, Float controlsPercentRecessive, Float quality, Integer numSamples, String variantType, VariantHardyWeinbergStats hw) {
    this.refAllele = refAllele;
    this.altAllele = altAllele;
    this.refAlleleCount = refAlleleCount;
    this.altAlleleCount = altAlleleCount;
    this.genotypesCount = genotypesCount;
    this.genotypesFreq = genotypesFreq;
    this.missingAlleles = missingAlleles;
    this.missingGenotypes = missingGenotypes;
    this.refAlleleFreq = refAlleleFreq;
    this.altAlleleFreq = altAlleleFreq;
    this.maf = maf;
    this.mgf = mgf;
    this.mafAllele = mafAllele;
    this.mgfGenotype = mgfGenotype;
    this.passedFilters = passedFilters;
    this.mendelianErrors = mendelianErrors;
    this.casesPercentDominant = casesPercentDominant;
    this.controlsPercentDominant = controlsPercentDominant;
    this.casesPercentRecessive = casesPercentRecessive;
    this.controlsPercentRecessive = controlsPercentRecessive;
    this.quality = quality;
    this.numSamples = numSamples;
    this.variantType = variantType;
    this.hw = hw;
  }
  
  /**
   * Gets the value of the 'refAllele' field.
   */
  public String getRefAllele() {
    return refAllele;
  }

  /**
   * Sets the value of the 'refAllele' field.
   * @param value the value to set.
   */
  public void setRefAllele(String value) {
    this.refAllele = value;
  }

  /**
   * Gets the value of the 'altAllele' field.
   */
  public String getAltAllele() {
    return altAllele;
  }

  /**
   * Sets the value of the 'altAllele' field.
   * @param value the value to set.
   */
  public void setAltAllele(String value) {
    this.altAllele = value;
  }

  /**
   * Gets the value of the 'refAlleleCount' field.
   */
  public Integer getRefAlleleCount() {
    return refAlleleCount;
  }

  /**
   * Sets the value of the 'refAlleleCount' field.
   * @param value the value to set.
   */
  public void setRefAlleleCount(Integer value) {
    this.refAlleleCount = value;
  }

  /**
   * Gets the value of the 'altAlleleCount' field.
   */
  public Integer getAltAlleleCount() {
    return altAlleleCount;
  }

  /**
   * Sets the value of the 'altAlleleCount' field.
   * @param value the value to set.
   */
  public void setAltAlleleCount(Integer value) {
    this.altAlleleCount = value;
  }

  /**
   * Gets the value of the 'genotypesCount' field.
   */
  public java.util.Map<String,Integer> getGenotypesCount() {
    return genotypesCount;
  }

  /**
   * Sets the value of the 'genotypesCount' field.
   * @param value the value to set.
   */
  public void setGenotypesCount(java.util.Map<String,Integer> value) {
    this.genotypesCount = value;
  }

  /**
   * Gets the value of the 'genotypesFreq' field.
   */
  public java.util.Map<String,Float> getGenotypesFreq() {
    return genotypesFreq;
  }

  /**
   * Sets the value of the 'genotypesFreq' field.
   * @param value the value to set.
   */
  public void setGenotypesFreq(java.util.Map<String,Float> value) {
    this.genotypesFreq = value;
  }

  /**
   * Gets the value of the 'missingAlleles' field.
   */
  public Integer getMissingAlleles() {
    return missingAlleles;
  }

  /**
   * Sets the value of the 'missingAlleles' field.
   * @param value the value to set.
   */
  public void setMissingAlleles(Integer value) {
    this.missingAlleles = value;
  }

  /**
   * Gets the value of the 'missingGenotypes' field.
   */
  public Integer getMissingGenotypes() {
    return missingGenotypes;
  }

  /**
   * Sets the value of the 'missingGenotypes' field.
   * @param value the value to set.
   */
  public void setMissingGenotypes(Integer value) {
    this.missingGenotypes = value;
  }

  /**
   * Gets the value of the 'refAlleleFreq' field.
   */
  public Float getRefAlleleFreq() {
    return refAlleleFreq;
  }

  /**
   * Sets the value of the 'refAlleleFreq' field.
   * @param value the value to set.
   */
  public void setRefAlleleFreq(Float value) {
    this.refAlleleFreq = value;
  }

  /**
   * Gets the value of the 'altAlleleFreq' field.
   */
  public Float getAltAlleleFreq() {
    return altAlleleFreq;
  }

  /**
   * Sets the value of the 'altAlleleFreq' field.
   * @param value the value to set.
   */
  public void setAltAlleleFreq(Float value) {
    this.altAlleleFreq = value;
  }

  /**
   * Gets the value of the 'maf' field.
   */
  public Float getMaf() {
    return maf;
  }

  /**
   * Sets the value of the 'maf' field.
   * @param value the value to set.
   */
  public void setMaf(Float value) {
    this.maf = value;
  }

  /**
   * Gets the value of the 'mgf' field.
   */
  public Float getMgf() {
    return mgf;
  }

  /**
   * Sets the value of the 'mgf' field.
   * @param value the value to set.
   */
  public void setMgf(Float value) {
    this.mgf = value;
  }

  /**
   * Gets the value of the 'mafAllele' field.
   */
  public String getMafAllele() {
    return mafAllele;
  }

  /**
   * Sets the value of the 'mafAllele' field.
   * @param value the value to set.
   */
  public void setMafAllele(String value) {
    this.mafAllele = value;
  }

  /**
   * Gets the value of the 'mgfGenotype' field.
   */
  public String getMgfGenotype() {
    return mgfGenotype;
  }

  /**
   * Sets the value of the 'mgfGenotype' field.
   * @param value the value to set.
   */
  public void setMgfGenotype(String value) {
    this.mgfGenotype = value;
  }

  /**
   * Gets the value of the 'passedFilters' field.
   */
  public Boolean getPassedFilters() {
    return passedFilters;
  }

  /**
   * Sets the value of the 'passedFilters' field.
   * @param value the value to set.
   */
  public void setPassedFilters(Boolean value) {
    this.passedFilters = value;
  }

  /**
   * Gets the value of the 'mendelianErrors' field.
   */
  public Integer getMendelianErrors() {
    return mendelianErrors;
  }

  /**
   * Sets the value of the 'mendelianErrors' field.
   * @param value the value to set.
   */
  public void setMendelianErrors(Integer value) {
    this.mendelianErrors = value;
  }

  /**
   * Gets the value of the 'casesPercentDominant' field.
   */
  public Float getCasesPercentDominant() {
    return casesPercentDominant;
  }

  /**
   * Sets the value of the 'casesPercentDominant' field.
   * @param value the value to set.
   */
  public void setCasesPercentDominant(Float value) {
    this.casesPercentDominant = value;
  }

  /**
   * Gets the value of the 'controlsPercentDominant' field.
   */
  public Float getControlsPercentDominant() {
    return controlsPercentDominant;
  }

  /**
   * Sets the value of the 'controlsPercentDominant' field.
   * @param value the value to set.
   */
  public void setControlsPercentDominant(Float value) {
    this.controlsPercentDominant = value;
  }

  /**
   * Gets the value of the 'casesPercentRecessive' field.
   */
  public Float getCasesPercentRecessive() {
    return casesPercentRecessive;
  }

  /**
   * Sets the value of the 'casesPercentRecessive' field.
   * @param value the value to set.
   */
  public void setCasesPercentRecessive(Float value) {
    this.casesPercentRecessive = value;
  }

  /**
   * Gets the value of the 'controlsPercentRecessive' field.
   */
  public Float getControlsPercentRecessive() {
    return controlsPercentRecessive;
  }

  /**
   * Sets the value of the 'controlsPercentRecessive' field.
   * @param value the value to set.
   */
  public void setControlsPercentRecessive(Float value) {
    this.controlsPercentRecessive = value;
  }

  /**
   * Gets the value of the 'quality' field.
   */
  public Float getQuality() {
    return quality;
  }

  /**
   * Sets the value of the 'quality' field.
   * @param value the value to set.
   */
  public void setQuality(Float value) {
    this.quality = value;
  }

  /**
   * Gets the value of the 'numSamples' field.
   */
  public Integer getNumSamples() {
    return numSamples;
  }

  /**
   * Sets the value of the 'numSamples' field.
   * @param value the value to set.
   */
  public void setNumSamples(Integer value) {
    this.numSamples = value;
  }

  /**
   * Gets the value of the 'variantType' field.
   */
  public String getVariantType() {
    return variantType;
  }

  /**
   * Sets the value of the 'variantType' field.
   * @param value the value to set.
   */
  public void setVariantType(String value) {
    this.variantType = value;
  }

  /**
   * Gets the value of the 'hw' field.
   */
  public VariantHardyWeinbergStats getHw() {
    return hw;
  }

  /**
   * Sets the value of the 'hw' field.
   * @param value the value to set.
   */
  public void setHw(VariantHardyWeinbergStats value) {
    this.hw = value;
  }
}
