/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.opencb.hpg.bigdata.app.cli.local.avro;
@SuppressWarnings("all")
/** Variant effect with Sequence Ontology terms.

* `SO_0002052`: dominant_negative_variant (http://purl.obolibrary.org/obo/SO_0002052)
* `SO_0002053`: gain_of_function_variant (http://purl.obolibrary.org/obo/SO_0002053)
* `SO_0001773`: lethal_variant (http://purl.obolibrary.org/obo/SO_0001773)
* `SO_0002054`: loss_of_function_variant (http://purl.obolibrary.org/obo/SO_0002054)
* `SO_0001786`: loss_of_heterozygosity (http://purl.obolibrary.org/obo/SO_0001786)
* `SO_0002055`: null_variant (http://purl.obolibrary.org/obo/SO_0002055) */
public enum VariantFunctionalEffect {
  dominant_negative_variant, gain_of_function_variant, lethal_variant, loss_of_function_variant, loss_of_heterozygosity, null_variant  ;
}
